# Generated by Django 4.2.6 on 2023-11-02 12:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import gist.models.activity


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("is_publish", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("add_at", models.DateTimeField(auto_now_add=True)),
                ("change_at", models.DateTimeField(auto_now=True)),
                (
                    "delete_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("active_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "deactivate_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("publish_at", models.DateTimeField(auto_now_add=True)),
                (
                    "unpublished_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "active_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(gist.models.activity.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_active_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "add_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(gist.models.activity.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_add_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "change_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(gist.models.activity.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_change_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deactivate_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(gist.models.activity.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_deactivate_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delete_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(gist.models.activity.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_delete_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "publish_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(gist.models.activity.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_publish_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unpublished_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(gist.models.activity.get_sentinel_user),
                        related_name="%(app_label)s_%(class)s_unpublished_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "bite_users",
                "ordering": ["-add_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
